version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - ineffassign  
    - misspell
    - errcheck
    - staticcheck
    - unused
    - gosec
    - nakedret
    - gocritic
    - gocyclo
    - unconvert
    - prealloc
    - dupl

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false

    gocyclo:
      min-complexity: 15

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style

    dupl:
      threshold: 100

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
